version: '3'
services:
  aerospike:
    image: aerospike/aerospike-server:latest
    ports:
      - "3000:3000"
      - "3001:3001"
      - "8081:8081"
    volumes:

      - ./data:/opt/aerospike/data

    networks:
      - aerospike-network
networks:
  aerospike-network:
    driver: bridge